version: '3.1'

services:
  db:
    image: postgres:14.5
    container_name: test
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres

      # - DB_PORT=5432
    restart: always
